export default {
    lan: "Русский",
    common: {
        meta: {
            description: "Официальный сайт LiveWallpaper",
            keywords: "Giantapp Wallpaper,LiveWallpaper,Dynamic Wallpaper,Free Wallpaper Engine,бесплатный Wallpaper Engine,живые обои,бесплатные живые обои",
        },
        validate: {
            required: "Это поле обязательно к заполнению",
            email: "В этом поле должен быть действующий адрес электронной почты.",
            password: "Пароль должен быть {min}-{max} буквенно-цифровой строкой",
            confirmPassword: "Подтверждение в этом поле не совпадает",
            max: "Максимальная длина: {max}"
        },
        appName: 'LiveWallpaper',
        studioName: 'Giantapp Studio',
        poweredBy: "Разработчик сайта: <a href='{url}'>{author}</a>",
        lanContribute: 'Сопровождающий вашего языка',
        signUp: "Зарегестрироваться",
        login: "Войти",
        findpassword: "Забыл пароль",
        wechatLogin: "Вход через WeChat",
        logout: "Выйти",
        copyright: "@2018-2020 - {studio}",
        videoWP: "Видео-обои",
        imageWP: "Обои-изображения",
        htmlWP: "Веб-обои",
        exeWP: "Обои-приложения",
        start: "Запустить",
        stop: "Остановить",
        close: "Закрыть",
        more: "Больше",
        settings: "Настройки",
        downloadClient: "Скачать клиент",
        wallpaper: "Обои",
        cover: "Обложка",
        home: "Домашняя",
        multiLanguage: "Многоязычный",
        save: "Сохранить",
        submit: "Отправить",
        disable: "Отключить",
        stop: "Остановить",
        pause: "Приостановить",
        play: "Воспроизвести",
        create: "Создать",
        noClient: "Похоже, что клиент LiveWallpaper не запущен",
        openClient: "Открыть клиент",
        afterOpenClientTips: "После открытия клиента обоев, необходимо обновить страницу, чтобы получить данные.",
        edit: "Редактировать",
        delete: "Удалить",
        cancel: "Отмена",
        refresh: "Обновить",
        installFFmpeg: 'Установить FFmpeg',
        needFFmpeg: "Вам необходимо установить FFmpeg, чтобы создавать скриншоты видео.",
        regenerate: "Регенерировать",
        clickToInstall: "Нажмите, чтобы установить",
        generatingCover: "Генерация обложки...",
        uploadCover: "Загрузить обложку",
        signedOut: "Вы вышли из системы!",
        email: "Эл. почта",
        oldPassword: "Старый пароль",
        password: "Пароль",
        confirmPassword: "Подтвердить пароль",
        uploaded: "Загружено"
    },
    home: {
        title: "",
        meta: {
            description: "",
            keywords: "",
        },
        intro: 'Изысканное приложение для Windows 10 с динамическими и статическими обоями с открытым исходным кодом',
        download1: "Установить",
        download2: "Ручная установка",
        whyUse1: "Бесплатно",
        whyUse1Tips: "Бесплатное использование, сосредоточьтесь на бесплатном ПО",
        whyUse2: "Открытый исходный код",
        whyUse2Tips: "Клиент с открытым исходным кодом на GitHub, не будь злым",
        whyUse3: "Легковесный",
        whyUse3Tips: "Простой и быстрый, никаких бесполезных функций связывания",
        whyUse4: "Сообщество",
        whyUse4Tips: "Легко загружайте, скачивайте любимые обои",
    },
    local: {
        title: "Локальные обои",
        meta: {
            description: "",
            keywords: "",
        },
        setupPlayerTip: 'Чтобы запустить {type} в первый раз, необходимо установить средство визуализации',
        customUrlTip: "Пользовательский URL-адрес скачивания",
        customUrlPlaceholder: "Введите пользовательский URL-адрес",
        downloading: 'Скачивание {progress}%',
        downloadComplete: 'Скачивание завершено',
        waitStart: 'Происходит запуск',
        unzipping: 'Распаковка {progress}%',
        unzipComplete: 'Распаковка завершена',
        noWallpapers: "Обоев пока нет",
        deletingWallpaper: "Удаление обоев",
        deletingWallpaperConfirmMessage: "Уверены, что хотите {delete} <b>{name}</b>? Эта операция фактически удалит файл и не может быть восстановлена.",
        wallpaperDeleted: 'Обои удалены',
        openFileDir: "Откройте каталог, в котором находится файл",
    },
    login: {
        title: "Вход в аккаунт",
        loginTips: `Производя вход, вы соглашаетесь с <a href='https://giantapp.cn/post/protocols/user-licence/' target='_blank'>Пользовательским соглашением </a> и <a target='_blank' href='https://giantapp.cn/post/protocols/privacy-pc/'>Политикой конфиденциальности </a>`,
    },
    register: {
        registerTips: `Я согласен с <a href='https://giantapp.cn/post/protocols/user-licence/' target='_blank'>Пользовательским соглашением </a> и <a target='_blank' href='https://giantapp.cn/post/protocols/privacy-pc/'>Политикой конфиденциальности </a>`
    },
    community: {
        title: "Сообщество обоев",
        meta: {
            description: "",
            keywords: "",
        },
    },
    dashboard: {
        menus: {
            content: "Содержимое",
            createWallpaper: "Создать",
            wallpapers: "Ваши обои",
            account: "Аккаунт",
            profile: "Профиль",
            setpwd: "Изменить пароль",
            client: "Клиент",
            localSettings: "Настройки",
            upload: "Загрузить",
        },
        wallpapers: {

        },
        client: {
            setting: {
                title: "Локальные настройки",
                general: "Общие",
                startWithSystem: "Запускать приложение при включении системы",
                appMaximizedEffectAllScreen: "Приостановить или остановить обои на всех экранах, когда есть окно на весь экран",
                audioScreen: "Исходный звук",
                thirdpartToolsDir: "Каталог сторонних инструментов",
                thirdpartToolsDirTips: "Например: C:\\LiveWallpaperTools\\",
                externalPlayerFolder: "Каталог средств визуализации обоев",
                externalPlayerFolderTips: "Например: C:\\LiveWallpaperPlayers\\",
                forwardMouseEvent: "Передать события мыши ",
                wallpaperSaveDir: "Каталог обоев",
                wallpaperSaveDirTips: "Например: C:\\LiveWallpaper\\",
                screenParameter: "Параметры {screenName}",
                whenAppMaximized: "Когда окно развёрнуто",
                savedSuccessfully: "Успешно сохранено",
                saveFailed: "Не удалось сохранить"
            },
            editor: {
                uploadTips: "Перетащите файл сюда или нажмите «Загрузить»",
                uploadCancelled: "Загрузка отменена",
                title: "Заголовок",
                titlePlaceholder: "Заголовок не может быть пустым",
                description: "Описание",
                descriptionPlaceholder: "Дайте описение совим обоям (необязательно)",
                original: "Оригинальные обои",
                originalTips: "Если вы являетесь автором этих обоев, установите этот флажок, иначе не устанавливайте",
                tag: "Теги",
                tagPlaceholder: "Добавьте теги к обоям, чтобы облегчить локальную классификацию. (Например: Игры, Пейзажи, Персонажи, WOW, LOL, и т.п.)",
                leaveTips: "Выйти без сохранения?"
            },
        },
    },
    client: {
        exit: "Выход"
    }
}
